<div id="company-info">	
	<div id="company_address">
		<div class="name">An Vat Aiya</div>
		<div class="address">12 Bui Thi Xuan</div>
		<div class="mobile">(+084) 8 4332 332</div>
		<div class="website">aiya.com.vn</div>
	</div>
	<div id="company_map">
		<img class="map-address" src="images/map.jpg" />
	</div>
	<div id="company_partner">
		<img class="partner" src="images/partner.jpg" />
		<img class="partner" src="images/partner.jpg" />
		<img class="partner" src="images/partner.jpg" />
	</div>
</div>