		
		
	</div>
	<div id="footer" >	
	<img class="border" src="images/border-footer.png">
			<div style="float:right">
				<div class="fb-like-box" data-href="https://www.facebook.com/timkmvn" 
				data-colorscheme="dark" data-show-faces="false" 
				data-header="false" data-stream="false" data-show-border="false"
				data-width="292" data-height="30"
				></div>
			</div>
		<div>
			
			<ul>
				<li><a href="#">Giới thiệu</a></li>
				<li><a href="term_timkm.php">Điều khoản sử dụng</a></li>
				<li><a href="#">Câu hỏi thường gặp</a></a></li>
				<li><a href="contact.php">Liên hệ với chúng tôi</a></a></li>	
					
			</ul>	
			
			<div class="copyright">
				Copyright© 2014 TimKM.vn
				
			</div>	
		</div>
    </div>
    <!--/div-->
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&appId=279877535393718&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>
