/*
 * This file was automatically generated By Code Smith 
 * Modifications will be overwritten when code smith is run
 *
 * PLEASE DO NOT MAKE MODIFICATIONS TO THIS FILE
 * Date Created 5/6/2012
 *
 */


var articleType = {	   
	
    //region Contants	
    ACT_ADD : 10,
    ACT_UPDATE : 11,
    ACT_DELETE : 12,
    ACT_CHANGE_PAGE : 13,
    ACT_SHOW_EDIT : 14,
    ACT_GET : 15,
	ACT_GET_ALL : 16,
    Page : "bg_article.php",
    
    AllCategories: null,
   
    //region Public Functions
    setAllCategories: function(){
		model = this;
		core.request.post(this.Page,
			{
				act:this.ACT_GET_ALL
			},
            function(respone, info){
				model.AllCategories = jQuery.parseJSON(respone);
				core.ui.hideInfoBar();
            },
            function()
            {
				core.ui.hideInfoBar();
            },false
        );
	},
	
	bindCategory: function(obj)
	{
		me = this;
		var categories = me.AllCategories;
		var currentParent = core.util.getObjectValueByID('cmArea');
		$("#cmCategory").empty();
		for (var item in categories) {
			if( categories[item].ParentID == currentParent)
			{				
				key = categories[item].ArticleTypeID;
				val =  categories[item].ArticleTypeName;			
				$("#cmCategory").append("<option value=\"" + key + "\">" + val + "</option>");
			}
		}
		$("#cmCategory").trigger("liszt:updated");
	},
    //endregion   
    
    //region Public Functions
    /*
    this.btnSave_OnClick = btnSave_OnClick;
    function btnSave_OnClick() {
        core.disableControl("btnOK", true);
        var isValid = true;

		var articleTypeID = core.trim(core.getObject("txtArticleTypeID").val());
		core.ValidateInputTextBox('txtArticleTypeID','');
		if(articleTypeID == ''){
			core.ValidateInputTextBox('txtArticleTypeID','ArticleTypeID is required', isValid);
			isValid =  false;
		}else if (articleTypeID.length > 20) {
			core.ValidateInputTextBox('txtArticleTypeID','ArticleTypeID must be less than 20', isValid);
			isValid =  false;
		}

		var articleTypeName = core.trim(core.getObject("txtArticleTypeName").val());
		core.ValidateInputTextBox('txtArticleTypeName','');
		if(articleTypeName == ''){
			core.ValidateInputTextBox('txtArticleTypeName','ArticleTypeName is required', isValid);
			isValid =  false;
		}else if (articleTypeName.length > 50) {
			core.ValidateInputTextBox('txtArticleTypeName','ArticleTypeName must be less than 50', isValid);
			isValid =  false;
		}

		var status = core.trim(core.getObject("txtStatus").val());
		core.ValidateInputTextBox('txtStatus','');
		if(status == ''){
			core.ValidateInputTextBox('txtStatus','Status is required', isValid);
			isValid =  false;
		}else if (status.length > 20) {
			core.ValidateInputTextBox('txtStatus','Status must be less than 20', isValid);
			isValid =  false;
		}

		var level = core.trim(core.getObject("txtLevel").val());
		core.ValidateInputTextBox('txtLevel','');
		if(level == ''){
			core.ValidateInputTextBox('txtLevel','Level is required', isValid);
			isValid =  false;
		}else if (level.length > 12) {
			core.ValidateInputTextBox('txtLevel','Level must be less than 0', isValid);
			isValid =  false;
		}
else if (core.isInteger(level)) {
			core.ValidateInputTextBox('txtLevel','Level is invalid', isValid);
		}

		var parentID = core.trim(core.getObject("txtParentID").val());
		core.ValidateInputTextBox('txtParentID','');
		if(parentID == ''){
			core.ValidateInputTextBox('txtParentID','ParentID is required', isValid);
			isValid =  false;
		}else if (parentID.length > 20) {
			core.ValidateInputTextBox('txtParentID','ParentID must be less than 20', isValid);
			isValid =  false;
		}

	       
        if (isValid == false) {
         core.disableControl("btnOK", false);
            return;
        }
         
        if (core.getObject("adddocmode")[0].value == ADD_MODE) {
            insertNew();
        }
        else {
            edit();
        }
    }
    
    this.edit = edit;
    function edit() {

		var articleTypeID = core.trim(core.getObject("txtArticleTypeID").val());
		var articleTypeName = core.trim(core.getObject("txtArticleTypeName").val());
		var status = core.trim(core.getObject("txtStatus").val());
		var level = core.trim(core.getObject("txtLevel").val());
		var parentID = core.trim(core.getObject("txtParentID").val());
	                
        strRequest = "?isAJ=1&act=" + ACT_UPDATE +  
            '&ArticleTypeID='+ core.urlencode(articleTypeID)+
			'&ArticleTypeName='+ core.urlencode(articleTypeName)+
			'&Status='+ core.urlencode(status)+
			'&Level='+ core.urlencode(level)+
			'&ParentID='+ core.urlencode(parentID)		;
        
        var ajax = new Ajax();
        ajax.SendRequestToServerWithCustomMsg(_strPage, strRequest, edit_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }

    function edit_OnCallBack(xmlHTTPRequest) {
        core.disableControl("btnOK", false);
        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    // ph?i kh?i t?o l?i d? tr?nh d?ng popdiv addFavourite
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', strRespond[1]["inf"]);
                    showAddMode();
                    changePage(_strPage, ACT_CHANGE_PAGE, core.getObject("txtPage").val());
                }
                else {
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    top.popDiv.childPop.alert(strRespond[1]["inf"], SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.insertNew = insertNew;
    function insertNew() {

		var articleTypeID = core.trim(core.getObject("txtArticleTypeID").val());
		var articleTypeName = core.trim(core.getObject("txtArticleTypeName").val());
		var status = core.trim(core.getObject("txtStatus").val());
		var level = core.trim(core.getObject("txtLevel").val());
		var parentID = core.trim(core.getObject("txtParentID").val());
	        
        strRequest = "?isAJ=1&act=" + ACT_ADD +  
            '&ArticleTypeID='+ core.urlencode(articleTypeID)+
			'&ArticleTypeName='+ core.urlencode(articleTypeName)+
			'&Status='+ core.urlencode(status)+
			'&Level='+ core.urlencode(level)+
			'&ParentID='+ core.urlencode(parentID)		;
        
        var ajax = new Ajax();
        ajax.SendRequestToServerWithCustomMsg(_strPage, strRequest, insertNew_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }

    function insertNew_OnCallBack(xmlHTTPRequest) {
        core.disableControl("btnOK", false);
        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    // ph?i kh?i t?o l?i d? tr?nh d?ng popdiv addFavourite
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', strRespond[1]["inf"]);
                    showAddMode();
                    changePage(_strPage, ACT_CHANGE_PAGE, 1);
                }
                else {
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    top.popDiv.childPop.alert(strRespond[1]["inf"], SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    var _cacheURL_pdoc;
    this.deleteObj = deleteObj;
    function deleteObj(id, name) {
        //curRow = currentRowId;
        popDiv.alert('Do you want to delete ' + name + ' ?', SYSTEM_TITLE_ERROR, 2, "_objArticleType.delete_OK()", "_objArticleType.delete_Cancel()");

        var keyword = '';
        if (typeof core.getObject("txtGet") != 'undefined') {
            keyword = core.getObject("txtGet").val();
        }
      
        _cacheURL_pdoc = _strPage + "?isAJ=1&act=" + ACT_DELETE + "&id=" + docid + "&p=" + core.getObject("txtPage")[0].value + "&kw=" + keyword;
    }
    this.delete_Cancel = delete_Cancel;
    function delete_Cancel() {
        //core.getObject("adddocmode")[0].value = ADD_MODE;
    }
    this.delete_OK = delete_OK;
    function delete_OK() {
        // Prepare AJAX to remove selected doc from favorite list
        var ajax = new Ajax(METHOD_GET);
        ajax.SendRequestToServerWithCustomMsg(_cacheURL_pdoc, null, delete_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }
    function delete_OnCallBack(xmlHTTPRequest) {

        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);

                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    parent.window.showInfoBar('success', strRespond[1]["inf"]);
                    core.getObject("txtPage")[0].value = strRespond[1]["p"];
                    popDiv.hide();
                    core.getObject("list-content")[0].innerHTML = strRespond[1]['list'];
                }
                else //if(parseInt(strRespond[3]) == -1)
                {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.showEdit = showEdit;
    function showEdit(strID) {
        showAddMode();
        strRequest = "?isAJ=1&act=" + ACT_SHOW_EDIT + "&id=" + strID; ;
        var ajax = new Ajax(METHOD_GET);
        ajax.SendRequestToServerWithCustomMsg(_strPage + strRequest, null, showEdit_OnCallBack, true, MSG_AJAX_FETCHING_VN);

    }
    function showEdit_OnCallBack(xmlHTTPRequest) {

        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', MSG_RES_OPERATION_SUCCESS);
                    //alert(strRespond[1]['sens']);
                    // Add Doc && clear field
					core.getObject('txtArticleTypeID').val(ArticleTypeID);
					core.getObject('txtArticleTypeName').val(ArticleTypeName);
					core.getObject('txtStatus').val(Status);
					core.getObject('txtLevel').val(Level);
					core.getObject('txtParentID').val(ParentID);
                    core.getObject("adddocmode")[0].value = EDIT_MODE;
                    core.getObject("status-add")[0].innerHTML = 'Edit mode';
                }
                else  // Duplicate
                {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.showAddMode = showAddMode;
    function showAddMode() {
        core.getObject("adddocmode")[0].value = ADD_MODE;
        core.getObject("status-add")[0].innerHTML = 'Add mode';
		core.getObject('txtArticleTypeID').val('');
		core.getObject('txtArticleTypeName').val('');
		core.getObject('txtStatus').val('');
		core.getObject('txtLevel').val('');
		core.getObject('txtParentID').val('');
    }
    //endregion   
	*/
}
//var _objArticleType = new  ArticleType();
