<?php
echo '<div class="article-content">';
echo '	<div class="zone-content">';
echo '		<div class="content-detail">';
echo '			<div class="zone-comment">';
echo '				<textarea id="comment-editor"></textarea>';
echo '				<div class="zone-control">';
echo '					<input type="button" value="Gửi" id="btnPostComment" class="btn-normal" />';
echo '					<input type="button" value="Hủy" id="btnCancel"  class="btn-normal" />';
echo '				</div>';
echo '			</div>';
echo '		</div>';
echo '	</div>';
echo '</div>';

?>