		
		
	</div>
	<div id="footer" >	
		<img class="border" src="images/border-footer.png">
		<ul>
			<li><a href="#">Liên hệ với chúng tôi</a></li>
			<li><a href="#">Điều khoản sử dụng</a></li>
			<li><a href="#">Câu hỏi thường gặp</a></a></li>
			<li><a href="#">Liên hệ với chúng tôi</a></a></li>			
        </ul>	
		<div class="copyright">
			Copyright© 2014 TimKM.vn
		</div>	
    </div>
    <!--/div-->
</div>
</body>
</html>
