<div class="pagination pull-right margin-right">
	<ul>
		<li><a href="#" title="Trang đầu tiên"><i class="icon-step-backward"></i></a></li>
		<li><a href="#" title="Trang trước">&laquo;</a></li>
		<li><a href="#">1</a></li>
		<li><a href="#">2</a></li>
		<li><a href="#">3</a></li>
		<li><a href="#">4</a></li>
		<li><a href="#">5</a></li>
		<li><a href="#" title="Trang sau">&raquo;</a></li>
		<li><a href="#" title="Trang cuối cùng"><i class="icon-step-forward"></i></a></li>
	</ul>
</div>