/*
 * This file was automatically generated By Code Smith 
 * Modifications will be overwritten when code smith is run
 *
 * PLEASE DO NOT MAKE MODIFICATIONS TO THIS FILE
 * Date Created 5/6/2012
 *
 */



/// <summary>
/// Implementations of sladtypes represent a AdType
///
/// </summary>
function AdType()
{		   
	//region PRESERVE ExtraMethods For AdType
	//endregion
    //region Contants	
    var ACT_ADD = 10;
    var ACT_UPDATE = 11;
    var ACT_DELETE = 12;
    var ACT_CHANGE_PAGE = 13;
    var ACT_SHOW_EDIT = 14;
    var ACT_GET = 15;
    var _strPage = "admin_adType.php";
    
   
    //endregion   
    
    //region Public Functions
    
    this.btnSave_OnClick = btnSave_OnClick;
    function btnSave_OnClick() {
        core.disableControl("btnOK", true);
        var isValid = true;

		var adTypeID = core.trim(core.getObject("txtAdTypeID").val());
		core.ValidateInputTextBox('txtAdTypeID','');
		if(adTypeID == ''){
			core.ValidateInputTextBox('txtAdTypeID','AdTypeID is required', isValid);
			isValid =  false;
		}else if (adTypeID.length > 20) {
			core.ValidateInputTextBox('txtAdTypeID','AdTypeID must be less than 20', isValid);
			isValid =  false;
		}

		var adTypeName = core.trim(core.getObject("txtAdTypeName").val());
		core.ValidateInputTextBox('txtAdTypeName','');
		if(adTypeName == ''){
			core.ValidateInputTextBox('txtAdTypeName','AdTypeName is required', isValid);
			isValid =  false;
		}else if (adTypeName.length > 50) {
			core.ValidateInputTextBox('txtAdTypeName','AdTypeName must be less than 50', isValid);
			isValid =  false;
		}

		var width = core.trim(core.getObject("txtWidth").val());
		core.ValidateInputTextBox('txtWidth','');
		if(width == ''){
			core.ValidateInputTextBox('txtWidth','Width is required', isValid);
			isValid =  false;
		}else if (width.length > 12) {
			core.ValidateInputTextBox('txtWidth','Width must be less than 0', isValid);
			isValid =  false;
		}
else if (core.isInteger(width)) {
			core.ValidateInputTextBox('txtWidth','Width is invalid', isValid);
		}

		var height = core.trim(core.getObject("txtHeight").val());
		core.ValidateInputTextBox('txtHeight','');
		if(height == ''){
			core.ValidateInputTextBox('txtHeight','Height is required', isValid);
			isValid =  false;
		}else if (height.length > 12) {
			core.ValidateInputTextBox('txtHeight','Height must be less than 0', isValid);
			isValid =  false;
		}
else if (core.isInteger(height)) {
			core.ValidateInputTextBox('txtHeight','Height is invalid', isValid);
		}

		var numOfDay = core.trim(core.getObject("txtNumOfDay").val());
		core.ValidateInputTextBox('txtNumOfDay','');
		if(numOfDay == ''){
			core.ValidateInputTextBox('txtNumOfDay','NumOfDay is required', isValid);
			isValid =  false;
		}else if (numOfDay.length > 12) {
			core.ValidateInputTextBox('txtNumOfDay','NumOfDay must be less than 0', isValid);
			isValid =  false;
		}
else if (core.isInteger(numOfDay)) {
			core.ValidateInputTextBox('txtNumOfDay','NumOfDay is invalid', isValid);
		}

		var displayPage = core.trim(core.getObject("txtDisplayPage").val());
		core.ValidateInputTextBox('txtDisplayPage','');
		if(displayPage == ''){
			core.ValidateInputTextBox('txtDisplayPage','DisplayPage is required', isValid);
			isValid =  false;
		}else if (displayPage.length > 20) {
			core.ValidateInputTextBox('txtDisplayPage','DisplayPage must be less than 20', isValid);
			isValid =  false;
		}

		var sharedItem = core.trim(core.getObject("txtSharedItem").val());
		core.ValidateInputTextBox('txtSharedItem','');
		if(sharedItem == ''){
			core.ValidateInputTextBox('txtSharedItem','SharedItem is required', isValid);
			isValid =  false;
		}else if (sharedItem.length > 12) {
			core.ValidateInputTextBox('txtSharedItem','SharedItem must be less than 0', isValid);
			isValid =  false;
		}
else if (core.isInteger(sharedItem)) {
			core.ValidateInputTextBox('txtSharedItem','SharedItem is invalid', isValid);
		}

		var price = core.trim(core.getObject("txtPrice").val());
		core.ValidateInputTextBox('txtPrice','');
		if(price == ''){
			core.ValidateInputTextBox('txtPrice','Price is required', isValid);
			isValid =  false;
		}
		var cityID = core.trim(core.getObject("txtCityID").val());
		core.ValidateInputTextBox('txtCityID','');
		if(cityID == ''){
			core.ValidateInputTextBox('txtCityID','CityID is required', isValid);
			isValid =  false;
		}else if (cityID.length > 20) {
			core.ValidateInputTextBox('txtCityID','CityID must be less than 20', isValid);
			isValid =  false;
		}

		var status = core.trim(core.getObject("txtStatus").val());
		core.ValidateInputTextBox('txtStatus','');
		if(status == ''){
			core.ValidateInputTextBox('txtStatus','Status is required', isValid);
			isValid =  false;
		}else if (status.length > 20) {
			core.ValidateInputTextBox('txtStatus','Status must be less than 20', isValid);
			isValid =  false;
		}

	       
        if (isValid == false) {
         core.disableControl("btnOK", false);
            return;
        }
         
        if (core.getObject("adddocmode")[0].value == ADD_MODE) {
            insertNew();
        }
        else {
            edit();
        }
    }
    
    this.edit = edit;
    function edit() {

		var adTypeID = core.trim(core.getObject("txtAdTypeID").val());
		var adTypeName = core.trim(core.getObject("txtAdTypeName").val());
		var width = core.trim(core.getObject("txtWidth").val());
		var height = core.trim(core.getObject("txtHeight").val());
		var numOfDay = core.trim(core.getObject("txtNumOfDay").val());
		var displayPage = core.trim(core.getObject("txtDisplayPage").val());
		var sharedItem = core.trim(core.getObject("txtSharedItem").val());
		var price = core.trim(core.getObject("txtPrice").val());
		var cityID = core.trim(core.getObject("txtCityID").val());
		var status = core.trim(core.getObject("txtStatus").val());
	                
        strRequest = "?isAJ=1&act=" + ACT_UPDATE +  
            '&AdTypeID='+ core.urlencode(adTypeID)+
			'&AdTypeName='+ core.urlencode(adTypeName)+
			'&Width='+ core.urlencode(width)+
			'&Height='+ core.urlencode(height)+
			'&NumOfDay='+ core.urlencode(numOfDay)+
			'&DisplayPage='+ core.urlencode(displayPage)+
			'&SharedItem='+ core.urlencode(sharedItem)+
			'&Price='+ core.urlencode(price)+
			'&CityID='+ core.urlencode(cityID)+
			'&Status='+ core.urlencode(status)		;
        
        var ajax = new Ajax();
        ajax.SendRequestToServerWithCustomMsg(_strPage, strRequest, edit_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }

    function edit_OnCallBack(xmlHTTPRequest) {
        core.disableControl("btnOK", false);
        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    // ph?i kh?i t?o l?i d? tr?nh d?ng popdiv addFavourite
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', strRespond[1]["inf"]);
                    showAddMode();
                    changePage(_strPage, ACT_CHANGE_PAGE, core.getObject("txtPage").val());
                }
                else {
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    top.popDiv.childPop.alert(strRespond[1]["inf"], SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.insertNew = insertNew;
    function insertNew() {

		var adTypeID = core.trim(core.getObject("txtAdTypeID").val());
		var adTypeName = core.trim(core.getObject("txtAdTypeName").val());
		var width = core.trim(core.getObject("txtWidth").val());
		var height = core.trim(core.getObject("txtHeight").val());
		var numOfDay = core.trim(core.getObject("txtNumOfDay").val());
		var displayPage = core.trim(core.getObject("txtDisplayPage").val());
		var sharedItem = core.trim(core.getObject("txtSharedItem").val());
		var price = core.trim(core.getObject("txtPrice").val());
		var cityID = core.trim(core.getObject("txtCityID").val());
		var status = core.trim(core.getObject("txtStatus").val());
	        
        strRequest = "?isAJ=1&act=" + ACT_ADD +  
            '&AdTypeID='+ core.urlencode(adTypeID)+
			'&AdTypeName='+ core.urlencode(adTypeName)+
			'&Width='+ core.urlencode(width)+
			'&Height='+ core.urlencode(height)+
			'&NumOfDay='+ core.urlencode(numOfDay)+
			'&DisplayPage='+ core.urlencode(displayPage)+
			'&SharedItem='+ core.urlencode(sharedItem)+
			'&Price='+ core.urlencode(price)+
			'&CityID='+ core.urlencode(cityID)+
			'&Status='+ core.urlencode(status)		;
        
        var ajax = new Ajax();
        ajax.SendRequestToServerWithCustomMsg(_strPage, strRequest, insertNew_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }

    function insertNew_OnCallBack(xmlHTTPRequest) {
        core.disableControl("btnOK", false);
        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    // ph?i kh?i t?o l?i d? tr?nh d?ng popdiv addFavourite
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', strRespond[1]["inf"]);
                    showAddMode();
                    changePage(_strPage, ACT_CHANGE_PAGE, 1);
                }
                else {
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    top.popDiv.childPop.alert(strRespond[1]["inf"], SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    var _cacheURL_pdoc;
    this.deleteObj = deleteObj;
    function deleteObj(id, name) {
        //curRow = currentRowId;
        popDiv.alert('Do you want to delete ' + name + ' ?', SYSTEM_TITLE_ERROR, 2, "_objAdType.delete_OK()", "_objAdType.delete_Cancel()");

        var keyword = '';
        if (typeof core.getObject("txtGet") != 'undefined') {
            keyword = core.getObject("txtGet").val();
        }
      
        _cacheURL_pdoc = _strPage + "?isAJ=1&act=" + ACT_DELETE + "&id=" + docid + "&p=" + core.getObject("txtPage")[0].value + "&kw=" + keyword;
    }
    this.delete_Cancel = delete_Cancel;
    function delete_Cancel() {
        //core.getObject("adddocmode")[0].value = ADD_MODE;
    }
    this.delete_OK = delete_OK;
    function delete_OK() {
        // Prepare AJAX to remove selected doc from favorite list
        var ajax = new Ajax(METHOD_GET);
        ajax.SendRequestToServerWithCustomMsg(_cacheURL_pdoc, null, delete_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }
    function delete_OnCallBack(xmlHTTPRequest) {

        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);

                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    parent.window.showInfoBar('success', strRespond[1]["inf"]);
                    core.getObject("txtPage")[0].value = strRespond[1]["p"];
                    popDiv.hide();
                    core.getObject("list-content")[0].innerHTML = strRespond[1]['list'];
                }
                else //if(parseInt(strRespond[3]) == -1)
                {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.showEdit = showEdit;
    function showEdit(strID) {
        showAddMode();
        strRequest = "?isAJ=1&act=" + ACT_SHOW_EDIT + "&id=" + strID; ;
        var ajax = new Ajax(METHOD_GET);
        ajax.SendRequestToServerWithCustomMsg(_strPage + strRequest, null, showEdit_OnCallBack, true, MSG_AJAX_FETCHING_VN);

    }
    function showEdit_OnCallBack(xmlHTTPRequest) {

        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', MSG_RES_OPERATION_SUCCESS);
                    //alert(strRespond[1]['sens']);
                    // Add Doc && clear field
					core.getObject('txtAdTypeID').val(AdTypeID);
					core.getObject('txtAdTypeName').val(AdTypeName);
					core.getObject('txtWidth').val(Width);
					core.getObject('txtHeight').val(Height);
					core.getObject('txtNumOfDay').val(NumOfDay);
					core.getObject('txtDisplayPage').val(DisplayPage);
					core.getObject('txtSharedItem').val(SharedItem);
					core.getObject('txtPrice').val(Price);
					core.getObject('txtCityID').val(CityID);
					core.getObject('txtStatus').val(Status);
                    core.getObject("adddocmode")[0].value = EDIT_MODE;
                    core.getObject("status-add")[0].innerHTML = 'Edit mode';
                }
                else  // Duplicate
                {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.showAddMode = showAddMode;
    function showAddMode() {
        core.getObject("adddocmode")[0].value = ADD_MODE;
        core.getObject("status-add")[0].innerHTML = 'Add mode';
		core.getObject('txtAdTypeID').val('');
		core.getObject('txtAdTypeName').val('');
		core.getObject('txtWidth').val('');
		core.getObject('txtHeight').val('');
		core.getObject('txtNumOfDay').val('');
		core.getObject('txtDisplayPage').val('');
		core.getObject('txtSharedItem').val('');
		core.getObject('txtPrice').val('');
		core.getObject('txtCityID').val('');
		core.getObject('txtStatus').val('');
    }
    //endregion   
}
var _objAdType = new  AdType();
