/*
 * This file was automatically generated By Code Smith 
 * Modifications will be overwritten when code smith is run
 *
 * PLEASE DO NOT MAKE MODIFICATIONS TO THIS FILE
 * Date Created 5/6/2012
 *
 */



/// <summary>
/// Implementations of slpropertys represent a Property
///
/// </summary>
function Property()
{		   
	//region PRESERVE ExtraMethods For Property
	//endregion
    //region Contants	
    var ACT_ADD = 10;
    var ACT_UPDATE = 11;
    var ACT_DELETE = 12;
    var ACT_CHANGE_PAGE = 13;
    var ACT_SHOW_EDIT = 14;
    var ACT_GET = 15;
    var _strPage = "admin_property.php";
    
   
    //endregion   
    
    //region Public Functions
    
    this.btnSave_OnClick = btnSave_OnClick;
    function btnSave_OnClick() {
        core.disableControl("btnOK", true);
        var isValid = true;

		var propertyID = core.trim(core.getObject("txtPropertyID").val());
		core.ValidateInputTextBox('txtPropertyID','');
		if(propertyID == ''){
			core.ValidateInputTextBox('txtPropertyID','PropertyID is required', isValid);
			isValid =  false;
		}else if (propertyID.length > 20) {
			core.ValidateInputTextBox('txtPropertyID','PropertyID must be less than 20', isValid);
			isValid =  false;
		}

		var propertyName = core.trim(core.getObject("txtPropertyName").val());
		core.ValidateInputTextBox('txtPropertyName','');
		if(propertyName == ''){
			core.ValidateInputTextBox('txtPropertyName','PropertyName is required', isValid);
			isValid =  false;
		}else if (propertyName.length > 50) {
			core.ValidateInputTextBox('txtPropertyName','PropertyName must be less than 50', isValid);
			isValid =  false;
		}

		var productID = core.trim(core.getObject("txtProductID").val());
		core.ValidateInputTextBox('txtProductID','');
		if(productID == ''){
			core.ValidateInputTextBox('txtProductID','ProductID is required', isValid);
			isValid =  false;
		}else if (productID.length > 20) {
			core.ValidateInputTextBox('txtProductID','ProductID must be less than 20', isValid);
			isValid =  false;
		}

		var propertyValue = core.trim(core.getObject("txtPropertyValue").val());
		core.ValidateInputTextBox('txtPropertyValue','');
		if(propertyValue == ''){
			core.ValidateInputTextBox('txtPropertyValue','PropertyValue is required', isValid);
			isValid =  false;
		}else if (propertyValue.length > 255) {
			core.ValidateInputTextBox('txtPropertyValue','PropertyValue must be less than 255', isValid);
			isValid =  false;
		}

		var dataTypeID = core.trim(core.getObject("txtDataTypeID").val());
		core.ValidateInputTextBox('txtDataTypeID','');
		if(dataTypeID == ''){
			core.ValidateInputTextBox('txtDataTypeID','DataTypeID is required', isValid);
			isValid =  false;
		}else if (dataTypeID.length > 20) {
			core.ValidateInputTextBox('txtDataTypeID','DataTypeID must be less than 20', isValid);
			isValid =  false;
		}

		var status = core.trim(core.getObject("txtStatus").val());
		core.ValidateInputTextBox('txtStatus','');
		if(status == ''){
			core.ValidateInputTextBox('txtStatus','Status is required', isValid);
			isValid =  false;
		}else if (status.length > 20) {
			core.ValidateInputTextBox('txtStatus','Status must be less than 20', isValid);
			isValid =  false;
		}

	       
        if (isValid == false) {
         core.disableControl("btnOK", false);
            return;
        }
         
        if (core.getObject("adddocmode")[0].value == ADD_MODE) {
            insertNew();
        }
        else {
            edit();
        }
    }
    
    this.edit = edit;
    function edit() {

		var propertyID = core.trim(core.getObject("txtPropertyID").val());
		var propertyName = core.trim(core.getObject("txtPropertyName").val());
		var productID = core.trim(core.getObject("txtProductID").val());
		var propertyValue = core.trim(core.getObject("txtPropertyValue").val());
		var dataTypeID = core.trim(core.getObject("txtDataTypeID").val());
		var status = core.trim(core.getObject("txtStatus").val());
	                
        strRequest = "?isAJ=1&act=" + ACT_UPDATE +  
            '&PropertyID='+ core.urlencode(propertyID)+
			'&PropertyName='+ core.urlencode(propertyName)+
			'&ProductID='+ core.urlencode(productID)+
			'&PropertyValue='+ core.urlencode(propertyValue)+
			'&DataTypeID='+ core.urlencode(dataTypeID)+
			'&Status='+ core.urlencode(status)		;
        
        var ajax = new Ajax();
        ajax.SendRequestToServerWithCustomMsg(_strPage, strRequest, edit_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }

    function edit_OnCallBack(xmlHTTPRequest) {
        core.disableControl("btnOK", false);
        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    // ph?i kh?i t?o l?i d? tr?nh d?ng popdiv addFavourite
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', strRespond[1]["inf"]);
                    showAddMode();
                    changePage(_strPage, ACT_CHANGE_PAGE, core.getObject("txtPage").val());
                }
                else {
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    top.popDiv.childPop.alert(strRespond[1]["inf"], SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.insertNew = insertNew;
    function insertNew() {

		var propertyID = core.trim(core.getObject("txtPropertyID").val());
		var propertyName = core.trim(core.getObject("txtPropertyName").val());
		var productID = core.trim(core.getObject("txtProductID").val());
		var propertyValue = core.trim(core.getObject("txtPropertyValue").val());
		var dataTypeID = core.trim(core.getObject("txtDataTypeID").val());
		var status = core.trim(core.getObject("txtStatus").val());
	        
        strRequest = "?isAJ=1&act=" + ACT_ADD +  
            '&PropertyID='+ core.urlencode(propertyID)+
			'&PropertyName='+ core.urlencode(propertyName)+
			'&ProductID='+ core.urlencode(productID)+
			'&PropertyValue='+ core.urlencode(propertyValue)+
			'&DataTypeID='+ core.urlencode(dataTypeID)+
			'&Status='+ core.urlencode(status)		;
        
        var ajax = new Ajax();
        ajax.SendRequestToServerWithCustomMsg(_strPage, strRequest, insertNew_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }

    function insertNew_OnCallBack(xmlHTTPRequest) {
        core.disableControl("btnOK", false);
        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    // ph?i kh?i t?o l?i d? tr?nh d?ng popdiv addFavourite
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', strRespond[1]["inf"]);
                    showAddMode();
                    changePage(_strPage, ACT_CHANGE_PAGE, 1);
                }
                else {
                    //var popDiv = new PopDiv();
                    //popDiv.init();
                    top.popDiv.childPop.alert(strRespond[1]["inf"], SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    var _cacheURL_pdoc;
    this.deleteObj = deleteObj;
    function deleteObj(id, name) {
        //curRow = currentRowId;
        popDiv.alert('Do you want to delete ' + name + ' ?', SYSTEM_TITLE_ERROR, 2, "_objProperty.delete_OK()", "_objProperty.delete_Cancel()");

        var keyword = '';
        if (typeof core.getObject("txtGet") != 'undefined') {
            keyword = core.getObject("txtGet").val();
        }
      
        _cacheURL_pdoc = _strPage + "?isAJ=1&act=" + ACT_DELETE + "&id=" + docid + "&p=" + core.getObject("txtPage")[0].value + "&kw=" + keyword;
    }
    this.delete_Cancel = delete_Cancel;
    function delete_Cancel() {
        //core.getObject("adddocmode")[0].value = ADD_MODE;
    }
    this.delete_OK = delete_OK;
    function delete_OK() {
        // Prepare AJAX to remove selected doc from favorite list
        var ajax = new Ajax(METHOD_GET);
        ajax.SendRequestToServerWithCustomMsg(_cacheURL_pdoc, null, delete_OnCallBack, true, MSG_AJAX_FETCHING_VN);
    }
    function delete_OnCallBack(xmlHTTPRequest) {

        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);

                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    parent.window.showInfoBar('success', strRespond[1]["inf"]);
                    core.getObject("txtPage")[0].value = strRespond[1]["p"];
                    popDiv.hide();
                    core.getObject("list-content")[0].innerHTML = strRespond[1]['list'];
                }
                else //if(parseInt(strRespond[3]) == -1)
                {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.showEdit = showEdit;
    function showEdit(strID) {
        showAddMode();
        strRequest = "?isAJ=1&act=" + ACT_SHOW_EDIT + "&id=" + strID; ;
        var ajax = new Ajax(METHOD_GET);
        ajax.SendRequestToServerWithCustomMsg(_strPage + strRequest, null, showEdit_OnCallBack, true, MSG_AJAX_FETCHING_VN);

    }
    function showEdit_OnCallBack(xmlHTTPRequest) {

        if (xmlHTTPRequest.readyState == 4) {
            if (xmlHTTPRequest.status == 200) {
                var strRespond = core.parserXML(xmlHTTPRequest.responseText);
                if (!core.headerProcessingArr(strRespond[0], Array(true, true, false))) {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                    return;
                }
                if (parseInt(strRespond[1]['rs']) == 1) {
                    showInfoBar('success', MSG_RES_OPERATION_SUCCESS);
                    //alert(strRespond[1]['sens']);
                    // Add Doc && clear field
					core.getObject('txtPropertyID').val(PropertyID);
					core.getObject('txtPropertyName').val(PropertyName);
					core.getObject('txtProductID').val(ProductID);
					core.getObject('txtPropertyValue').val(PropertyValue);
					core.getObject('txtDataTypeID').val(DataTypeID);
					core.getObject('txtStatus').val(Status);
                    core.getObject("adddocmode")[0].value = EDIT_MODE;
                    core.getObject("status-add")[0].innerHTML = 'Edit mode';
                }
                else  // Duplicate
                {
                    popDiv.alert(MSG_RES_OPERATION_FAIL, SYSTEM_TITLE_ERROR, 1);
                }
            }
        }
    }
    
    this.showAddMode = showAddMode;
    function showAddMode() {
        core.getObject("adddocmode")[0].value = ADD_MODE;
        core.getObject("status-add")[0].innerHTML = 'Add mode';
		core.getObject('txtPropertyID').val('');
		core.getObject('txtPropertyName').val('');
		core.getObject('txtProductID').val('');
		core.getObject('txtPropertyValue').val('');
		core.getObject('txtDataTypeID').val('');
		core.getObject('txtStatus').val('');
    }
    //endregion   
}
var _objProperty = new  Property();
